# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cdp.api_key: '%env(CDP_API_KEY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

  # In Symfony, the _instanceof configuration key allows you to automatically apply configuration settings to all 
    # services that implement a specific interface or extend a certain class. This is very useful for applying tags, 
    # method calls, or other configuration options uniformly across multiple services without needing to configure each one individually.
    _instanceof:
        App\Handler\WebhookHandlerInterface:
            tags: [ 'webhook.handler' ]
        App\Forwarder\Newsletter\ForwarderInterface:
            tags: [ 'forwarder.newsletter' ]


    # Services which will be doubled for tests, better to use the test environment as multiple requests to the Frontend
    App\CDP\Http\CdpClientInterface: '@App\CDP\Http\CdpClient'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Wir teilen dem Container mit explizit wo der FakeCdpClient zu finden ist, da
    # der Test-Ordner nicht im src-Ordner liegt und vom Container nicht automatisch gefunden werden kann.

    # This service is used to send the request to the CDP API
when@test:
    services:
        App\Tests\TestDoubles\CDP\Http\FakeCdpClient: ~
        App\CDP\Http\CdpClientInterface: '@App\Tests\TestDoubles\CDP\Http\FakeCdpClient'